# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dark.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication
import pandas as pd
from io import StringIO


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(330, 70, 101, 51))
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(33, 56, 271, 291))
        self.textEdit.setObjectName("textEdit")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(450, 50, 301, 311))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 20, 72, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(490, 20, 72, 15))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "确定"))
        self.label.setText(_translate("MainWindow", "输入"))
        self.label_2.setText(_translate("MainWindow", "结果"))
        self.pushButton.clicked.connect(self.jj)

    def printf(self, mes):
        self.textBrowser.append(mes)  # 在指定的区域显示提示信息
        self.cursot = self.textBrowser.textCursor()
        self.textBrowser.moveCursor(self.cursot.End)
        QtWidgets.QApplication.processEvents()
    def jj(self):
        name = self.textEdit.toPlainText()
        csv_data = pd.read_csv(StringIO(name), low_memory=False)
        x = pd.DataFrame(csv_data)
        x = x.iloc[:, 1:].T

        # 1、数据序列预处理
        # x_mean = x.mean(axis=1)
        # x_max = x.max(axis=1)
        # x_min = x.min(axis=1)
        # for i in range(x.index.size):
        #    x.iloc[i, :] = x.iloc[i, :] / x_mean[i]
        #    x.iloc[i,:] = x.iloc[i,:]/x_min[i]
        #    x.iloc[i,:] = x.iloc[i,:]/x_max[i]

        # 2、提取参考队列和比较队列
        ck = x.iloc[0, :]
        cp = x.iloc[1:, :]

        # 比较队列与参考队列相减
        t = pd.DataFrame()
        for j in range(cp.index.size):
            temp = pd.Series(cp.iloc[j, :] - ck)
            t = t.append(temp, ignore_index=True)

        # 求最大差和最小差
        mmax = t.abs().max().max()
        mmin = t.abs().min().min()
        rho = 0.5

        # 3、求关联系数
        ksi = ((mmin + rho * mmax) / (abs(t) + rho * mmax))

        # 4、求关联度
        r = ksi.sum(axis=1) / ksi.columns.size

        # 5、关联度排序

        result = r.sort_values(ascending=False)
        self.textBrowser.append(str(result))
        self.cursot = self.textBrowser.textCursor()
        self.textBrowser.moveCursor(self.cursot.End)
        QtWidgets.QApplication.processEvents()





if __name__ == '__main__':
    import sys
    from PyQt5.QtWidgets import QApplication, QMainWindow
    #import pics_ui_rc # 导入添加的资源（根据实际情况填写文件名）
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

